name: Check & Deploy
on: push

jobs:
  deploy-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyPI Deployment
      uses: casperdcl/deploy-pypi@v2.2.1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        pip: wheel -w dist/ --no-deps .
        # only upload if a tag is pushed (otherwise just build & check)
        upload: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}